name: catfishsense1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  provider: ^6.0.0
  shared_preferences: ^2.0.11
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.2.16
  firebase_database: ^11.1.4
  http: ^1.2.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1 # Launcher icon configuration

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Config for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_launcher_icon.png" # Ensure this file exists
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/adaptive_foreground_icon.png" # Ensure this file exists

# Config for flutter_native_splash
flutter_native_splash:
  image: assets/images/adaptive_foreground_icon.png # Path to the splash screen image
  color: "#87CEEB" # Background color of splash screen
  android: true # Enable splash screen for Android
  ios: false # Disable splash screen for iOS
  web: false # Disable splash screen for Web
  android_gravity: center
  fullscreen: true
